//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint bind_overlay_modifier {
            get {
                return ((uint)(this["bind_overlay_modifier"]));
            }
            set {
                this["bind_overlay_modifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83")]
        public uint bind_overlay_key {
            get {
                return ((uint)(this["bind_overlay_key"]));
            }
            set {
                this["bind_overlay_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint bind_staff_show_modifier {
            get {
                return ((uint)(this["bind_staff_show_modifier"]));
            }
            set {
                this["bind_staff_show_modifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("88")]
        public uint bind_staff_show_key {
            get {
                return ((uint)(this["bind_staff_show_key"]));
            }
            set {
                this["bind_staff_show_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint bind_staff_po_modifier {
            get {
                return ((uint)(this["bind_staff_po_modifier"]));
            }
            set {
                this["bind_staff_po_modifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69")]
        public uint bind_staff_po_key {
            get {
                return ((uint)(this["bind_staff_po_key"]));
            }
            set {
                this["bind_staff_po_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enable_afk {
            get {
                return ((bool)(this["enable_afk"]));
            }
            set {
                this["enable_afk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enable_discord_actvity {
            get {
                return ((bool)(this["enable_discord_actvity"]));
            }
            set {
                this["enable_discord_actvity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-64bit -textmode -single_core -nojoy -low -nosound -sw -noshader -nopix -novid -n" +
            "opreload -nopreloadmodels -multirun +connect rp.superiorservers.co")]
        public string afk_arguments {
            get {
                return ((string)(this["afk_arguments"]));
            }
            set {
                this["afk_arguments"] = value;
            }
        }
    }
}
